---
system:
  name: "GhostLFS"
  version: "1.0.0"
  architecture: "x86_64"
  target_triplet: "x86_64-ghost-linux-gnu"

build:
  parallel_jobs: 4
  optimization: "-O2"
  debug_info: true
  strip_binaries: false

toolchain:
  binutils_version: "2.37"
  gcc_version: "11.2.0"
  glibc_version: "2.34"
  linux_version: "5.13.12"

features:
  security:
    enable_selinux: true
    enable_apparmor: false
    enable_hardening: true
    
  system:
    enable_systemd: true
    enable_network_manager: true
    enable_pulseaudio: true
    
  desktop:
    enable_xorg: true
    enable_wayland: true
    default_de: "xfce4"
    
  development:
    enable_development_tools: true
    enable_debugging_tools: true
    programming_languages:
      - cpp
      - python
      - rust
      - go

packages:
  base:
    - name: "bash"
      version: "5.1.8"
      critical: true
    - name: "coreutils"
      version: "8.32"
      critical: true
    - name: "systemd"
      version: "249"
      critical: true

  desktop:
    - name: "xorg-server"
      version: "21.1.1"
    - name: "xfce4"
      version: "4.16"
    - name: "firefox"
      version: "91.0"

  development:
    - name: "gcc"
      version: "11.2.0"
    - name: "gdb"
      version: "10.2"
    - name: "git"
      version: "2.33.0"

  security:
    - name: "selinux"
      version: "3.2"
    - name: "apparmor"
      version: "3.0.3"
    - name: "audit"
      version: "3.0.5"

paths:
  sources: "/mnt/lfs/sources"
  tools: "/mnt/lfs/tools"
  build: "/mnt/lfs/build"
  root: "/mnt/lfs"
  
scripts:
  pre_build: "scripts/pre_build.sh"
  post_build: "scripts/post_build.sh"
  error_handler: "scripts/error_handler.sh"
  
logging:
  level: "info"
  file: "build.log"
  verbose: true
  keep_logs: 5
