name: Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch
          git checkout -b gh-pages
          rm -rf *
          cp -r docs/* .
          git add .
          git commit -m "Deploy documentation"
          git push -f origin gh-pages
