name: Deploy Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git with token-based authentication
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          
          # Create and populate docs directory
          mkdir -p docs
          
          # Copy C++ docs if they exist
          if [ -d "projects/ghost_os_cpp/docs/html" ]; then
            cp -r projects/ghost_os_cpp/docs/html/* docs/
          fi
          
          # Copy curriculum docs if they exist
          if [ -d "projects/cpp_learning_lab/curriculum" ]; then
            mkdir -p docs/curriculum
            cp -r projects/cpp_learning_lab/curriculum/* docs/curriculum/
          fi
          
          # Create index file
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Project Documentation</title>
            <meta http-equiv="refresh" content="0; url=./curriculum/README.html">
          </head>
          <body>
            <p>Redirecting to documentation...</p>
          </body>
          </html>' > docs/index.html
          
          # Create and switch to gh-pages branch
          git checkout --orphan gh-pages
          git rm -rf .
          
          # Move docs to root
          mv docs/* .
          rm -rf docs
          
          # Add .nojekyll file
          touch .nojekyll
          
          # Commit and push
          git add -A
          git commit -m "Deploy documentation"
          git push -f origin gh-pages
