name: Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create a temporary directory for docs
          mkdir -p temp_docs
          
          # Copy all documentation
          cp -r projects/ghost_os_cpp/docs/html/* temp_docs/ || true
          cp -r projects/ghost_os_toolkit/target/doc/* temp_docs/ || true
          cp -r projects/cpp_learning_lab/curriculum/* temp_docs/ || true
          
          # Switch to gh-pages branch
          git checkout --orphan gh-pages
          git reset --hard
          
          # Remove everything except .git and temp_docs
          find . -maxdepth 1 ! -name '.git' ! -name 'temp_docs' -exec rm -rf {} +
          
          # Move docs to root and cleanup
          mv temp_docs/* .
          rm -rf temp_docs
          
          # Create necessary files
          touch .nojekyll
          echo '<meta http-equiv="refresh" content="0; url=./html/index.html">' > index.html
          
          # Commit and push
          git add -A
          git commit -m "Deploy documentation"
          git push -f origin gh-pages
