name: Deploy Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git with token-based authentication
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          
          # Create and populate docs directory
          rm -rf docs
          mkdir -p docs
          
          # Copy C++ docs if they exist
          if [ -d "projects/ghost_os_cpp/docs/html" ]; then
            mkdir -p docs/cpp
            cp -r projects/ghost_os_cpp/docs/html/* docs/cpp/
          fi
          
          # Copy curriculum docs if they exist
          if [ -d "projects/cpp_learning_lab/curriculum" ]; then
            mkdir -p docs/learning_lab
            cp -r projects/cpp_learning_lab/curriculum/* docs/learning_lab/
            
            # Convert README.md to HTML if pandoc is available
            if command -v pandoc &> /dev/null; then
              pandoc -f markdown -t html projects/cpp_learning_lab/curriculum/README.md -o docs/learning_lab/README.html
            else
              cp projects/cpp_learning_lab/curriculum/README.md docs/learning_lab/README.md
            fi
          fi
          
          # Create main index file
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Project Documentation</title>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; margin: 40px; }
              h1 { color: #333; }
              .nav-links { margin: 20px 0; }
              .nav-links a { 
                display: block;
                margin: 10px 0;
                color: #0366d6;
                text-decoration: none;
              }
              .nav-links a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <h1>Project Documentation</h1>
            <div class="nav-links">
              <a href="./cpp/">C++ Documentation</a>
              <a href="./learning_lab/">Learning Lab Curriculum</a>
            </div>
          </body>
          </html>' > docs/index.html
          
          # Switch to gh-pages branch
          git checkout --orphan gh-pages
          git reset --hard
          git add docs/
          git mv docs/* .
          rm -rf docs
          
          # Commit and push to gh-pages
          git commit -m "Deploy documentation to GitHub Pages"
          git push origin gh-pages --force
