name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: |
          npm install -g http-server

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare build directory
        run: |
          mkdir -p build
          # Copy main files
          cp index.html build/
          cp .nojekyll build/
          cp README.md build/
          cp CHANGELOG.md build/
          cp LICENSE build/
          cp CONTRIBUTING.md build/
          
          # Copy directories
          cp -r src build/
          cp -r assets build/
          cp -r docs build/
          cp -r projects build/
          cp -r backend build/
          
          # Create directory listing for navigation
          echo "Creating directory listing..."
          find build -type f > build/files.txt
          
          # Ensure all directories have proper permissions
          chmod -R 755 build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
